--SPRING/SPRING

CREATE TABLE SCORE(
    NUM NUMBER(10),
    NAME VARCHAR2(30),
    KOR VARCHAR2(30),
    ENG VARCHAR2(30),
    MATH VARCHAR2(30)
);

ALTER TABLE SCORE ADD CONSTRAINT SCORE_PK PRIMARY KEY (NUM);
DESC SCORE;
CREATE SEQUENCE SCORE_SEQ START WITH 1
  INCREMENT BY 1 NOCACHE;
  
select * from score;

CREATE TABLE BOARD(
    NUM NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(30),
    TITLE VARCHAR2(100),
    CONTENT VARCHAR2(200)
);
DESC BOARD;
CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;
select * from board;

select sysdate from dual;

select * from board where name like '%홍길동%' and title = '테스트6';

